title: "SSPA — Scientific Software Tools & Parallel Algorithms (2025)"
author: "L. Heltai"
launch_buttons:
  notebook_interface: "jupyterlab"
execute:
  execute_notebooks: "off"

logo: logo.png
copyright: "2025" # Update copyright year to 2025
only_build_toc_files: true

repository:
  url: https://github.com/luca-heltai/sspa # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true

extra_footer: |
  <p>Personal homepage: <a href="https://luca-heltai.github-io.com">luca-heltai.github-io.com</a></p>
