name: Lab09 Python - Run Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/sspa
  IMAGE_TAG: latest-python

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run pytest
        run: pytest -q
