name: Lab09 C++ - Run Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/sspa
  IMAGE_TAG: latest-cpp

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run ctest
        run: |
          cmake -S codes/lab09/cpp -B build
          cmake --build build
          ctest --test-dir build --output-on-failure
